// Domain categories and their tags (union of old and new)
export const DOMAIN_CATEGORIES = {
  '🧠 Technology & Data': [
    'Software Development',
    'Software Development / Engineering',
    'Web & App Development',
    'Web Development',
    'Mobile App Development',
    'Data Science',
    'Data Science & Analytics',
    'Artificial Intelligence / Machine Learning',
    'Cybersecurity',
    'Cloud Computing & DevOps',
    'Cloud Computing / DevOps',
    'UI/UX Design',
    'Product Management',
    'Data Engineering',
    'IT Support / Systems Administration',
    'IT Support / System Administration',
    'Blockchain & Web3',
    'Blockchain / Web3',
    'Game Development',
    'Game Design / Development',
    'AR/VR / Metaverse Design',
    'AR / VR Development',
  ],
  '💼 Business & Management': [
    'Business Strategy',
    'Business Strategy / Consulting',
    'Operations Management',
    'Project Management',
    'Consulting',
    'Entrepreneurship / Startups',
    'Product Marketing',
    'Marketing & Advertising',
    'Business Analysis',
    'Supply Chain & Logistics',
    'Supply Chain / Logistics',
    'Procurement & Vendor Management',
    'Human Resources / Talent Acquisition',
    'Sales & Business Development',
    'Finance & Accounting',
    'Customer Success / Client Relations',
  ],
  '📈 Marketing, Media & Communication': [
    'Digital Marketing',
    'Social Media Management',
    'Content Creation / Copywriting',
    'Writing / Content Creation',
    'SEO / SEM',
    'Brand Strategy',
    'Public Relations',
    'Public Relations / Communications',
    'Advertising',
    'Video Production / Editing',
    'Influencer Marketing',
    'Journalism',
  ],
  '💰 Finance & Economics': [
    'Accounting',
    'Financial Analysis',
    'Investment Banking',
    'Wealth Management',
    'Risk & Compliance',
    'FinTech',
    'Business Economics',
    'Venture Capital / Private Equity',
  ],
  '🧬 Science, Engineering & Research': [
    'Mechanical Engineering',
    'Electrical / Electronics Engineering',
    'Civil Engineering',
    'Civil / Structural Engineering',
    'Chemical Engineering',
    'Environmental Science',
    'Environmental Science / Sustainability',
    'Biotechnology',
    'Biotechnology / Biomedical Engineering',
    'Research & Development',
    'Renewable Energy',
    'Aerospace Engineering',
    'Physics / Chemistry / Mathematics Research',
    'Robotics / Automation',
  ],
  '🎨 Creative, Design & Arts': [
    'Graphic Design',
    'Illustration / Animation',
    'Animation / Motion Graphics',
    'Photography / Videography',
    'Photography',
    'Fashion Design',
    'Fashion / Interior Design',
    'Interior Design',
    'Music / Audio Production',
    'Writing / Storytelling',
    'Film & Theatre',
    'Brand Strategy',
  ],
  '🌍 Social Impact, Education & Humanities': [
    'Education & Training',
    'Teaching / Curriculum Design',
    'Educational Technology (EdTech)',
    'Training / Coaching',
    'Psychology / Counseling',
    'Psychology / Mental Health',
    'Sociology / Anthropology',
    'Nonprofit / NGO Management',
    'Social Work / Nonprofit',
    'Public Policy / Governance',
    'Policy / Governance',
    'Community Development',
    'Journalism / Media Studies',
    'Linguistics / Language Studies',
  ],
  '⚖️ Law, Policy & Government': [
    'Legal Practice',
    'Corporate Law',
    'Corporate Law / Compliance',
    'International Relations',
    'Political Science',
    'Public Administration',
    'Civil Services / Administration',
    'Legal Research',
    'Policy Analysis',
    'Public Policy',
  ],
  '💊 Healthcare & Wellness': [
    'Medicine',
    'Medicine / Nursing',
    'Nursing',
    'Public Health',
    'Nutrition & Dietetics',
    'Nutrition / Dietetics',
    'Physiotherapy',
    'Mental Health',
    'Fitness & Sports Science',
    'Pharmacy',
    'Veterinary Science',
    'Medical Research / Lab Work',
  ],
  '🏗️ Trades, Services & Other Domains': [
    'Real Estate',
    'Architecture',
    'Construction',
    'Hospitality & Tourism',
    'Customer Service',
    'Human Resources',
    'Retail & E-commerce',
    'E-commerce / D2C',
    'Manufacturing',
    'Logistics / Transport',
  ],
  '💡 Emerging Fields': [
    'Blockchain / Web3',
    'AR / VR Development',
    'Space Technology',
    'Green Tech / Renewable Energy',
    'E-commerce / D2C',
    'AI Product Design',
    'Ethical Tech / Responsible AI',
  ],
};

// Flattened list for backward compatibility
export const DOMAINS = Object.values(DOMAIN_CATEGORIES).flat();

// Common skills
export const SKILLS = [
  'Product Management',
  'Engineering',
  'Design',
  'Marketing',
  'Sales',
  'Data Science',
  'Backend Development',
  'Frontend Development',
  'Mobile Development',
  'DevOps',
  'Business Development',
  'Fundraising',
  'Operations',
  'Customer Success',
  'Content Writing',
];

// Common languages
export const LANGUAGES = [
  'English',
  'Spanish',
  'Mandarin',
  'Hindi',
  'French',
  'German',
  'Portuguese',
  'Japanese',
  'Korean',
  'Arabic',
  'Bengali',
  'Russian',
  'Italian',
  'Turkish',
  'Vietnamese',
  'Urdu',
  'Indonesian',
  'Thai',
  'Polish',
  'Dutch',
  'Swedish',
  'Persian',
  'Hebrew',
  'Tamil',
  'Telugu',
  'Marathi',
  'Gujarati',
  'Punjabi',
  'Ukrainian',
  'Greek',
];

